### ISSUE TITLE
@Permission这个注解是在哪里验证权限的？

### ISSUE THREAD

**Issue by chimisu** [choerodon/iam-service#10]
如题，IAM Service工程中没找到，在其他工程中吗？麻烦指明下，谢谢。

**Comment by devane001** [comment]
https://github.com/choerodon/api-gateway

**Comment by chimisu** [comment]
@wmzzh117 不是这个repo吧？我是想问，在哪对@Permission注解做反射，进行权限校验的。我看choerodon-starters中有PermissionProcessor，但是没看明白如何结合IAM Service去校验权限的。

**Comment by devane001** [comment]
权限校验的逻辑是在api-gateway 里面实现的。iam service 只是将权限进行统一的管理和分配。

**Comment by chimisu** [comment]
那@Permission注解既然放到了IAM Service Controller中的方法上，那我想知道@Permision在哪做的拦截校验。请告诉一下，谢谢。

**Comment by devane001** [comment]
- `@Permission` 注解是用来标明接口的权限。
- 统一的解析`@Permission` 是在`iam-service` 中，会将权限数据初始化到数据库。
- 校验接口权限是`api-gateway`通过拦截器查询数据库的数据来校验的。

具体代码实现可以将这两个库 clone 到本地查看。
