### ISSUE TITLE
Initial data out of date

### ISSUE THREAD

**Issue by minliacom** [choerodon/iam-service#2]
In iam-service project, no any menu entries found in 2018-03-27-init-data.xlsx file. when I login to system, no menu to click, how can I fix this? 

Thanks a million.

**Comment by devane001** [comment]
The menu is initialized through the front end. In another project [choerodon-front](https://github.com/choerodon/choerodon-front).

Etc.:
You can use [choerodon-front-boot](https://github.com/choerodon/choerodon-front-boot#init-menu) initialize menu entries.
