### ISSUE TITLE
choerodon.starters.version 的问题

### ISSUE THREAD

**Issue by yezhoujie** [choerodon/iam-service#3]
choerodon.starters.version 使用的是0.7.0 但是找不到0.7.0的jar包，无法编译

**Comment by devane001** [comment]
master分支的代码为我们正在开发的代码，部分依赖还没有发布。你可以拉取最新tag 的代码进行编译

**Comment by devane001** [comment]
> choerodon.starters.version 使用的是0.7.0 但是找不到0.7.0的jar包，无法编译

0.7.0 版本已经发布到公库上了，源码可以在这个地址上找到
https://github.com/choerodon/choerodon-starters/tree/0.7.0
