### ISSUE TITLE
用户信息表唯一索引问题

### ISSUE THREAD

**Issue by RavenCM** [choerodon/iam-service#4]
用户信息表(`iam_user`)中有两个唯一索引`phone`和`email`。
```text
iam_user_u2	`email`	UNIQUE
iam_user_u3	`phone`	UNIQUE
```
现在有一个场景是用户从企业A中离职，在企业B中入职，但是企业A需要保留离职用户的信息做记录，这时候用户如果使用同一个手机号或者邮箱就无法在企业B中注册。

`Choerodon`平台应该也存在类似的应用场景，不知道有没有计划解决方案。

**Comment by devane001** [comment]
@RavenCM 

这里确实有一点问题，目前主要的应用场景还是针对企业内`PAAS`平台，所以做了邮箱和手机号的限制，`SAAS`平台确实有局限。不过如果加上邮箱和手机号登录的话，全局唯一还是有必要的。

对于用户而言，不同企业内的企业邮箱一般不会相同，不过`Choerodon` 本身也是以登录名作为主键的，如果不同企业的登录名逻辑相同，可能会有冲突。

如果你们有相应的需求，可以根据组织code + 登录名做主键，做到全局唯一，不过在登录的处理上可能需要用户手动去选择企业。
