### ISSUE TITLE
发送站内信报错，LDAP账户同步时,数据为空,最终发送站内信报错

### ISSUE THREAD

**Issue by coolintan** [choerodon/iam-service#5]
OrganizationUserServiceImpl.batchCreateUsers()中insertUsers为null,会继续执行下面的startSaga(), 导致发送导致发送站内信报错
推荐: 当用户为空时, 不发送saga

**Comment by superlee007** [comment]
你好，请问iam用的什么版本，然后反馈下错误信息。
最新的同步是有做insertUsers.isEmpty()判断的，而且同步用户不发送站内信，只是把新增用户信息发送saga事件然后供其他服务消费

**Comment by coolintan** [comment]
看了你们最新版本也有这个问题, 批量创建用户如下代码
![image](https://user-images.githubusercontent.com/6115335/53215616-6b98ad00-368c-11e9-9373-5c8601a74a01.png)
推荐改为如图所示, 增加判断

**Comment by superlee9527** [comment]
明白了，谢谢反馈

**Comment by superlee007** [comment]
好的，多谢反馈，我们完善下这块
